# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1bd2ece7c467361a60c5825e5c29d936e204c251038e250f9e97af6d4c9edc1fc305ddb2b8b644e2ef39d9b4cec97676dedf66a0026222206c2eafa49f2b8be

test:
  secret_key_base: f1a72a76569ad409536f1ed60c7ae3c31cf3816477cd59baf08342a9ff727c8ed648b80a80792f275121b3d1658e65934632c28179cf24ca2af9ab45c4f3c97e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
